// <auto-generated />
namespace localshop.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_OrderStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_OrderStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202002181427131_Add_OrderStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
